get rel_version automatically

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -4,6 +4,8 @@ trigger:
 - master
 - release-*
 
+name: $(Date:yyyyMMdd)$(Rev:.r)
+
 variables:
   GOPATH: '$(system.defaultWorkingDirectory)/gopath'
   GOBIN:  '$(GOPATH)/bin'
@@ -35,14 +37,36 @@ jobs:
     targetOS: windows
     targetArch: amd64
     binaryExtension: '.exe'
-- job: publish_edge_binaries
+- job: release_environment
   pool:
-    vmImage: 'windows-2019'
+    vmImage: ubuntu-latest
+  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release-')
+  steps:
+    - script: |
+        SOURCEBRANCH=$(Build.SourceBranchName)
+        echo Source branch name : $SOURCEBRANCH
+        BRANCH_VERSION=${SOURCEBRANCH#release-}
+        echo Release branch version : $BRANCH_VERSION
+        
+        RELEASE_VERSION=$(git tag -l "v$BRANCH_VERSION-*" | tail -1)
+        [ -z "$RELEASE_VERSION" ] && echo "Cannot find the release version tag!" && exit 1
+        
+        RELVERSION=${RELEASE_VERSION#v*}
+        echo Release Version in tag : $RELVERSION
+        echo "##vso[task.setvariable variable=REL_VERSION;isOutput=true]$RELVERSION"
+      name: env_var_step
+- job: publish_edge_binaries
+  name: actions_$(Date:yyyyMMdd)$(Rev:.r)
+  pool:
+    vmImage: windows-2019
   dependsOn:
     - build_darwin_amd64
     - build_linux_amd64
     - build_linux_arm
     - build_windows_amd64
+    - release_environment
+  variables:
+    REL_VERSION: $[ dependencies.release_environment.outputs['env_var_step.REL_VERSION'] ]
   condition: |
     and
     (
@@ -53,25 +77,14 @@ jobs:
       ne(variables['Build.Reason'], 'PullRequest')
     )
   steps:
-    # binaries from master will be stored in edge/[date_revision] folder in blob storage
+    # binaries from master will be stored in edge/[branch_date.revision] folder in blob storage
     - script: |
-        echo ##vso[task.setvariable variable=BlobPrefix]$(Date:yyyyMMdd)_$(Rev:.r)
+        echo ##vso[task.setvariable variable=BlobPrefix]$(Build.BuildNumber)
         echo ##vso[task.setvariable variable=TargetContainer]edge
       condition: not(startsWith(variables['Build.SourceBranch'], 'refs/heads/release-'))
     # binaries from release-* will be stored in release/release version folder in blob storage
     - script: |
-        SOURCEBRANCH=$(Build.SourceBranchName)
-        echo source branch name : $SOURCEBRANCH
-        BRANCH_VERSION=${SOURCEBRANCH#release-}
-        echo release branch version : $BRANCH_VERSION
-        
-        RELEASE_VERSION=$(git tag -l "v$BRANCH_VERSION-*" | tail -1)
-        [ -z "$RELEASE_VERSION" ] && echo "Cannot find the release version tag" && exit 1
-        
-        RELVERSION=${RELEASE_VERSION#v*}
-        echo ##vso[task.setvariable variable=REL_VERSION;isOutput=true]$RELVERSION
-
-        echo ##vso[task.setvariable variable=BlobPrefix]$(RELVERSION)
+        echo ##vso[task.setvariable variable=BlobPrefix]$(REL_VERSION)
         echo ##vso[task.setvariable variable=TargetContainer]release
       name: releaseSetup
       condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release-')
@@ -99,30 +112,21 @@ jobs:
         storage: 'actionsreleases'
         ContainerName: '$(TargetContainer)'
         blobPrefix: 'latest'
-- job: 'build_and_push_amd64_docker_image'
+- job: 'build_and_push_docker_image'
   pool: 
     vmImage: 'ubuntu-latest'
   dependsOn:
     - publish_edge_binaries
+    - release_environment
   condition: |
     eq(dependencies.publish_edge_binaries.result, 'Succeeded')
   variables:
-    REL_VERSION: $[ dependencies.publish_edge_binaries.outputs['releaseSetup.REL_VERSION'] ]
+    REL_VERSION: $[ dependencies.release_environment.outputs['env_var_step.REL_VERSION'] ]
   steps:
     - template: 'build-and-push-image-template.yml'
       parameters:
         targetArch: amd64
         releaseVersion: $(REL_VERSION)
-- job: 'build_and_push_arm_docker_image'
-  pool: 
-    vmImage: 'ubuntu-latest'
-  dependsOn:
-    - publish_edge_binaries
-  condition: |
-    eq(dependencies.publish_edge_binaries.result, 'Succeeded')
-  variables:
-    REL_VERSION: $[ dependencies.publish_edge_binaries.outputs['releaseSetup.REL_VERSION'] ]
-  steps:
     - template: 'build-and-push-image-template.yml'
       parameters:
         targetArch: arm
