Use REL_VERSION parsed from branch-name and tag and simplify build process (#318)
* Instead of using hard-coded REL_VERSION, parse the version from release-* branch and tag
edge_build change
* (bug fix) Publish release-* build to /release/vX.X.X-alpha and /release/latest in blob storage
* Publish normal build to /edge/[build number] and /edge/latest in blob storage
* Simplify binary build process and docker image build processes
* Add GOPROXY

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -10,147 +10,103 @@ variables:
   modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'
   BlobPrefix: ''
 
+name: $(Date:yyyyMMdd)$(Rev:.r)
+
 jobs:
 - template: 'build-binary-template.yml'
   parameters:
     poolImage: macOS-latest
     targetOS: darwin
     targetArch: amd64
-    binaryName: actionsrt
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: macOS-latest
-    targetOS: darwin
-    targetArch: amd64
-    binaryName: injector
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: macOS-latest
-    targetOS: darwin
-    targetArch: amd64
-    binaryName: placement
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: macOS-latest
-    targetOS: darwin
-    targetArch: amd64
-    binaryName: operator
+    binaryExtension: ''
 - template: 'build-binary-template.yml'
   parameters:
     poolImage: ubuntu-latest
     targetOS: linux
     targetArch: arm
-    binaryName: actionsrt
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: ubuntu-latest
-    targetOS: linux
-    targetArch: arm
-    binaryName: injector
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: ubuntu-latest
-    targetOS: linux
-    targetArch: arm
-    binaryName: placement
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: ubuntu-latest
-    targetOS: linux
-    targetArch: arm
-    binaryName: operator
+    binaryExtension: ''
 - template: 'build-binary-template.yml'
   parameters:
     poolImage: ubuntu-latest
     targetOS: linux
     targetArch: amd64
-    binaryName: actionsrt
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: ubuntu-latest
-    targetOS: linux
-    targetArch: amd64
-    binaryName: injector
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: ubuntu-latest
-    targetOS: linux
-    targetArch: amd64
-    binaryName: placement
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: ubuntu-latest
-    targetOS: linux
-    targetArch: amd64
-    binaryName: operator
+    binaryExtension: ''
 - template: 'build-binary-template.yml'
   parameters:
     poolImage: windows-2019
     targetOS: windows
     targetArch: amd64
-    binaryName: actionsrt
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: windows-2019
-    targetOS: windows
-    targetArch: amd64
-    binaryName: injector
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: windows-2019
-    targetOS: windows
-    targetArch: amd64
-    binaryName: placement
-- template: 'build-binary-template.yml'
-  parameters:
-    poolImage: windows-2019
-    targetOS: windows
-    targetArch: amd64
-    binaryName: operator
-- job: 'publish_edge_binaries'
+    binaryExtension: '.exe'
+- job: release_environment
   pool:
-    vmImage: 'windows-2019'
+    vmImage: ubuntu-latest
+  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release-')
+  steps:
+    - script: |
+        SOURCEBRANCH=$(Build.SourceBranchName)
+        echo Source branch name : $SOURCEBRANCH
+        BRANCH_VERSION=${SOURCEBRANCH#release-}
+        echo Release branch version : $BRANCH_VERSION
+        
+        RELEASE_VERSION=$(git tag -l "v$BRANCH_VERSION-*" | tail -1)
+        [ -z "$RELEASE_VERSION" ] && echo "Cannot find the release version tag!" && exit 1
+        
+        RELVERSION=${RELEASE_VERSION#v*}
+        echo Release Version in tag : $RELVERSION
+  
+        echo "##vso[task.setvariable variable=REL_VERSION;isOutput=true]$RELVERSION"
+        echo $RELVERSION > $(Build.ArtifactStagingDirectory)/release_version.txt
+        echo $(Build.SourceVersion) > $(Build.ArtifactStagingDirectory)/release_commit_id.txt
+
+        echo Checking release note for $RELVERSION...
+        RELNOTE_PATH="docs/release_notes/v$RELVERSION.md"
+        if [ -f "$RELNOTE_PATH" ]; then
+          echo Found release note $RELNOTE_PATH and copying to artifact directory
+          cp $RELNOTE_PATH $(Build.ArtifactStagingDirectory)/release_note.md
+          echo Add release tag
+          echo "##vso[build.addbuildtag]release"
+        else
+          echo Skip releasing release note. this is not final release.
+        fi
+      name: env_var_step
+    - task: PublishBuildArtifacts@1
+      displayName: 'Publish build artifacts'
+      inputs:
+        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
+        ArtifactName: 'drop'
+        publishLocation: 'Container'
+- job: publish_edge_binaries
+  pool:
+    vmImage: windows-2019
   dependsOn:
-  - build_darwin_amd64_actionsrt
-  - build_darwin_amd64_injector
-  - build_darwin_amd64_placement
-  - build_darwin_amd64_operator
-  - build_linux_amd64_actionsrt
-  - build_linux_amd64_injector
-  - build_linux_amd64_placement
-  - build_linux_amd64_operator
-  - build_linux_arm_actionsrt
-  - build_linux_arm_injector
-  - build_linux_arm_placement
-  - build_linux_arm_operator
-  - build_windows_amd64_actionsrt
-  - build_windows_amd64_injector
-  - build_windows_amd64_placement
-  - build_windows_amd64_operator
+    - build_darwin_amd64
+    - build_linux_amd64
+    - build_linux_arm
+    - build_windows_amd64
+    - release_environment
+  variables:
+    REL_VERSION: $[ dependencies.release_environment.outputs['env_var_step.REL_VERSION'] ]
   condition: |
     and
     (
-      eq(dependencies.build_darwin_amd64_actionsrt.result, 'Succeeded'),
-      eq(dependencies.build_darwin_amd64_injector.result, 'Succeeded'),
-      eq(dependencies.build_darwin_amd64_placement.result, 'Succeeded'),
-      eq(dependencies.build_darwin_amd64_operator.result, 'Succeeded'),
-      eq(dependencies.build_linux_amd64_actionsrt.result, 'Succeeded'),
-      eq(dependencies.build_linux_amd64_injector.result, 'Succeeded'),
-      eq(dependencies.build_linux_amd64_placement.result, 'Succeeded'),
-      eq(dependencies.build_linux_amd64_operator.result, 'Succeeded'),
-      eq(dependencies.build_linux_arm_actionsrt.result, 'Succeeded'),
-      eq(dependencies.build_linux_arm_injector.result, 'Succeeded'),
-      eq(dependencies.build_linux_arm_placement.result, 'Succeeded'),
-      eq(dependencies.build_linux_arm_operator.result, 'Succeeded'),
-      eq(dependencies.build_windows_amd64_actionsrt.result, 'Succeeded'),
-      eq(dependencies.build_windows_amd64_injector.result, 'Succeeded'),
-      eq(dependencies.build_windows_amd64_placement.result, 'Succeeded'),
-      eq(dependencies.build_windows_amd64_operator.result, 'Succeeded'),
+      eq(dependencies.build_darwin_amd64.result, 'Succeeded'),
+      eq(dependencies.build_linux_amd64.result, 'Succeeded'),
+      eq(dependencies.build_linux_arm.result, 'Succeeded'),
+      eq(dependencies.build_windows_amd64.result, 'Succeeded'),
       ne(variables['Build.Reason'], 'PullRequest')
     )
   steps:
-    - script: echo '##vso[task.setvariable variable=BlobPrefix]$(Build.SourceBranchName)/$(REL_VERSION)
+    # binaries from master will be stored in edge/[branch_date.revision] folder in blob storage
+    - script: |
+        echo ##vso[task.setvariable variable=BlobPrefix]$(Build.BuildNumber)
+        echo ##vso[task.setvariable variable=TargetContainer]edge
       condition: not(startsWith(variables['Build.SourceBranch'], 'refs/heads/release-'))
+    # binaries from release-* will be stored in release/release version folder in blob storage
+    - script: |
+        echo ##vso[task.setvariable variable=BlobPrefix]$(REL_VERSION)
+        echo ##vso[task.setvariable variable=TargetContainer]release
+      name: releaseSetup
+      condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release-')
     - task: DownloadPipelineArtifact@2
       displayName: 'Download pipeline artifacts to workspace'
       inputs:
@@ -158,39 +114,39 @@ jobs:
         itemPattern: '**/*.zip'
         targetPath: '$(Pipeline.Workspace)'
     - task: AzureFileCopy@3
-      displayName: 'Publish archives to blob storage'
+      displayName: 'Publish archives to version folder'
       inputs:
         SourcePath: '$(Pipeline.Workspace)/drop'
         azureSubscription: 'Actions Releases'
         Destination: 'AzureBlob'
         storage: 'actionsreleases'
-        ContainerName: 'bin'
+        ContainerName: '$(TargetContainer)'
         blobPrefix: '$(BlobPrefix)'
-- job: 'build_and_push_amd64_docker_image'
-  variables:
-    DockerVersionTag: ''
-    DockerReleaseTag: ''
+    - task: AzureFileCopy@3
+      displayName: 'Publish archives to latest folder'
+      inputs:
+        SourcePath: '$(Pipeline.Workspace)/drop'
+        azureSubscription: 'Actions Releases'
+        Destination: 'AzureBlob'
+        storage: 'actionsreleases'
+        ContainerName: '$(TargetContainer)'
+        blobPrefix: 'latest'
+- job: 'build_and_push_docker_image'
   pool: 
     vmImage: 'ubuntu-latest'
   dependsOn:
     - publish_edge_binaries
+    - release_environment
   condition: |
     eq(dependencies.publish_edge_binaries.result, 'Succeeded')
+  variables:
+    REL_VERSION: $[ dependencies.release_environment.outputs['env_var_step.REL_VERSION'] ]
   steps:
     - template: 'build-and-push-image-template.yml'
       parameters:
         targetArch: amd64
-- job: 'build_and_push_arm_docker_image'
-  variables:
-    DockerVersionTag: ''
-    DockerReleaseTag: ''
-  pool: 
-    vmImage: 'ubuntu-latest'
-  dependsOn:
-    - publish_edge_binaries
-  condition: |
-    eq(dependencies.publish_edge_binaries.result, 'Succeeded')
-  steps:
+        releaseVersion: $(REL_VERSION)
     - template: 'build-and-push-image-template.yml'
       parameters:
         targetArch: arm
+        releaseVersion: $(REL_VERSION)
